runtime: go
api_version: go1
instance_class: F1

default_expiration: '1d'

automatic_scaling:
  max_concurrent_requests: 64
  max_idle_instances: automatic

handlers:
  - url: /.*
    script: _go_app
    secure: always
    redirect_http_response_code: 301

skip_files:
  - ^(.*/)?.*\.DS_Store$
  - node_modules/
  - .vscode/
  - old/
  - bin/
  - dev/ #used for development
  - src/
  - test/
  - public/
  - README.md
  - .eslintrc.js
  - .gitignore
  - settings.json
  - tsconfig.json
  - vue.config.js
  - package.json
  - yarn.lock
  - yarn-error.log

env_variables:
  ENVIRONMENT: 'master'
  DIST_FOLDER: 'dist'
  GAE_DATASTORE_HOST: 'moms-lost-marbles.appspot.com'
