runtime: go112
instance_class: F1

default_expiration: '1d'

automatic_scaling:
  max_concurrent_requests: 64
  max_idle_instances: automatic

handlers:
  - url: /.*
    script: _go_app
    secure: always
    redirect_http_response_code: 301

env_variables:
  ENVIRONMENT: 'master'
  DIST_FOLDER: 'dist'
  CLOUD_STORAGE_BUCKET: 'moms-lost-marbles.appspot.com'
